import type { Metadata } from "next";
import "./globals.css";
import "../lib/constants/font";
import LayoutContainer from "@/components/ui/layout";

export const metadata: Metadata = {
	// title: 'Create Next App',
	// description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="dark:bg-[#0C0A09] duration-300">
				<LayoutContainer>{children}</LayoutContainer>
			</body>
		</html>
	);
}
